// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjzp9mkDNvsqVBcMnvw-P_Aufg1uoe_E',
    appId: '1:954519984654:web:65101b07859155956e3a5f',
    messagingSenderId: '954519984654',
    projectId: 'trouver-442f0',
    authDomain: 'trouver-442f0.firebaseapp.com',
    storageBucket: 'trouver-442f0.appspot.com',
    measurementId: 'G-K8C7EKM6XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOfC6Jl8ORnmoOY4fXopac0ACCUqCdCo',
    appId: '1:954519984654:android:ff4e780070037ec56e3a5f',
    messagingSenderId: '954519984654',
    projectId: 'trouver-442f0',
    storageBucket: 'trouver-442f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBky1CGdCmNBahkK1eAy825V7JLCx7L7Zw',
    appId: '1:954519984654:ios:e63b545df327031b6e3a5f',
    messagingSenderId: '954519984654',
    projectId: 'trouver-442f0',
    storageBucket: 'trouver-442f0.appspot.com',
    iosClientId: '954519984654-gb8u94i20k318vpn3ba42cqnmbht6lnc.apps.googleusercontent.com',
    iosBundleId: 'com.trouver.trouver',
  );
}
